### pandas was created by wes mckinney in 2008.
### pandas is a python library which helps us in data analysis and data modification. it can clean the messy data and make it readable and understandable.
### Data analysis is a process of inspecting, cleansing, transforming, and modeling data with the goal of discovering useful information, informing conclusions, and supporting decision_making
### Data analysis is done by two methods 1) visualization --> in which we make graphs of data, and 2) Analysis--> which includes all the processes of the data.
### There are three types of data structures used in pandas.
### 1)Series, 2) data frames, and 3) Panels

In [1]:
# import the libraries
import pandas as pd
import numpy as np

# 1) Series:
### deals with 1D data conataining arrays 
### --> pd.Series(array/list/dic etc, index=[anything for indexing] , dtype='', name="")

In [2]:
# making a simple series
s1=pd.Series(12)
print(s1) # this will print 12 at index 0

0    12
dtype: int64


In [3]:
# to make a series of many same numbers withe different indices
s2=pd.Series(12, index=[1,2,3,4,5,6,7,8,9]) 
print(s2) # this will print 12 at 9 different indices

1    12
2    12
3    12
4    12
5    12
6    12
7    12
8    12
9    12
dtype: int64


In [4]:
# other examples
a=np.array([1,2,3,4,5,6]) # it is not necessary to make array bcz a simple list can also work
print("\nThe series of array 'a' without defining indices is\n",pd.Series(a)) # a series will be printed with indices staring with 0 by default
 


The series of array 'a' without defining indices is
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [5]:
 
# making series by giving indices of our own choice using above mentioned array 'a'
b=pd.Series(a, index=['one','two', 'three', 'four','five', 'six'], dtype="int32", name="Simple Series")
print("\nThe Series of array 'a' with indices, datatype and name defined, is\n", b)



The Series of array 'a' with indices, datatype and name defined, is
 one      1
two      2
three    3
four     4
five     5
six      6
Name: Simple Series, dtype: int32


In [6]:

# we can also pass dictionary, tuple, sets etc to make a series
dic={"name":['Haji', 'Khan', 'Imran'], "age":[19, 20, 69], "designation":['Student', 'Teacher', 'Maalik']}
d=pd.Series(dic) # here Keys/Names work as names of rows bcz index=[] is defined, if defined the keys will work as column names
print("\nthe series of a dictionary 'dic' is\n ", d)



the series of a dictionary 'dic' is
  name                  [Haji, Khan, Imran]
age                          [19, 20, 69]
designation    [Student, Teacher, Maalik]
dtype: object


In [7]:

# mathematics on series (+, -, *, /)
s2=pd.Series(12, index=[1,2,3,4,5,6,7,8,9])
# b=pd.Series(s2)
a=np.array([1,2,3,4,5,6])
c=pd.Series(a, index=[1,2,3,4,5,6])
print("\nThe sum of elements of two arrays is\n", s2+c) # this will add the elements but the length of first series is greater than that of sencond, therefore, the elements which are not added a NAN will be printed inplace of those elements. 



The sum of elements of two arrays is
 1    13.0
2    14.0
3    15.0
4    16.0
5    17.0
6    18.0
7     NaN
8     NaN
9     NaN
dtype: float64


# 2) Data Frames
### 2D data conataining arrays much like a table
### --> pd.Dataframe(array/list/dic etc, )

In [8]:
# making simple data frame
arr=np.array([1,2,3,4,5,6,7]) # simple list can also be used 
a=pd.DataFrame(arr)
print("\nThe data frame of array 'a' is\n", a) # this will print a table of data containing rows and columns 



The data frame of array 'a' is
    0
0  1
1  2
2  3
3  4
4  5
5  6
6  7


In [9]:
# making data frame using dictionary in which "Key" will work as column name and :value will work as data, while the row indexing will be same as default unless we bring change in it
###### the data in dictionary must be balanced otherwise it will throw an error.#####
dic={"name":['Haji', 'Khan', 'Imran'], "age":[19, 20, 69], "designation":['Student', 'Teacher', 'Maalik']}
d=pd.DataFrame(dic , index=['value1', 'value2', 'value3']) # if index is not give than it will be printed as 0,1,2,...
print("\nthe data farme of a dictionary 'dic' is\n ", d)



the data farme of a dictionary 'dic' is
           name  age designation
value1   Haji   19     Student
value2   Khan   20     Teacher
value3  Imran   69      Maalik


In [10]:

# to see the data of desired column
# --> pd.dataframe(array, columns=['name'])
dic={"name":['Haji', 'Khan', 'Imran'], "age":[19, 20, 69], "designation":['Student', 'Teacher', 'Maalik']}
d=pd.DataFrame(dic , index=['value1', 'value2', 'value3'], columns=['name'])
print("\nThe data of column 'name' of dic is\n", d) # the data of provided column will be displayed



The data of column 'name' of dic is
          name
value1   Haji
value2   Khan
value3  Imran


In [11]:

# extarct the desired value from the data frame
# --> ["column name/Key"][row/index]
d=pd.DataFrame(dic , index=['value1', 'value2', 'value3'])
print(d["age"]['value2']) # this will print value from column age and row value2


20


In [12]:

# making data frame from an multidimensional arrays  or list of list
ar=np.array([[11,22,33,44,55], [66,77,88,99,100]])
a_1=pd.DataFrame(ar, index=['r1', 'r2'], columns=['v1', 'v2', 'v3', 'v4', 'v5']) # columns[''] serves as the names of columns
print("\n the dataframe from a 2D array is\n", a_1)



 the dataframe from a 2D array is
     v1  v2  v3  v4   v5
r1  11  22  33  44   55
r2  66  77  88  99  100


In [13]:

# making data frame using Series
sr={"s1":pd.Series([1,2,3,4,5]), "s2":pd.Series([22,33,44,55,66])} # s1 and s2 serves as the names of columns
s=pd.DataFrame(sr)
print("\nThe dataframe using Series is \n", s)



The dataframe using Series is 
    s1  s2
0   1  22
1   2  33
2   3  44
3   4  55
4   5  66


### Arithimatic on pandas (+,-,*,/)

In [14]:
# adding two columns and save the data in another column and than make it the part of the same data frame
a=pd.DataFrame({"Column_1":[1,2,3,4,5], "Column_2":[11,22,33,44,55]})
a["Column_3"]=a["Column_1"]+a["Column_2"] # here the elements of the col1 and col2 are adding and saved in col 3 of df 'a'
# we can also perform any arithematic operation b/w the columns as mentioned in parenthesis above
print("\nThe data frame after adding two coulmns is\n",a) # will print the data of above three columns



The data frame after adding two coulmns is
    Column_1  Column_2  Column_3
0         1        11        12
1         2        22        24
2         3        33        36
3         4        44        48
4         5        55        60


In [15]:

# Comparing two values of the same column
val=pd.DataFrame({"A":[11,22,33,44], "B":[55,66,77,88]}, index=["val1", "val2", "val3", "val4"])
comp=pd.DataFrame(val["A"] <=30)
print("\nAfter comparing the data frame obtained is\n", comp) # will return the boolean answer 



After comparing the data frame obtained is
           A
val1   True
val2   True
val3  False
val4  False


In [16]:

# now in order to add the compared column to the data frame 
val=pd.DataFrame({"A":[11,22,33,44], "B":[55,66,77,88]}, index=["val1", "val2", "val3", "val4"])
val["copm1"] = val["A"] <=30 # this will return the boolean answer in the same data frame
val["copm2"] = val["B"] >=60
print("\nAfter comparing the data frame along with the copmared column is\n", val)



After comparing the data frame along with the copmared column is
        A   B  copm1  copm2
val1  11  55   True  False
val2  22  66   True   True
val3  33  77  False   True
val4  44  88  False   True


In [17]:

# adding the desired copy elements from one column to the new one
# here the slicing[:] is used
val=pd.DataFrame({"Column_1":[1,2,3,4,5], "Column_2":[11,22,33,44,55]})
val["Desired_val"]=val["Column_1"][:3] # this will copy the top most three elements in a new column
print("\nAfter copying the deisred elements the data frame is\n", val) # a NAN is printed in the place of non copied elements



After copying the deisred elements the data frame is
    Column_1  Column_2  Desired_val
0         1        11          1.0
1         2        22          2.0
2         3        33          3.0
3         4        44          NaN
4         5        55          NaN


### Delete and Insert functions

In [18]:
# inserting any column in a ndata frame 
# name.insert(column position, "new column name", values or to make same copy of the column as-->column["column name"])
v=pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]}, index=['r1', 'r2', 'r3', 'r4'])
v.insert(2,"C", [11,22,33,44]) # this will add a new column C at the position 3
v.insert(2, "Copy of A", v["A"]) # this will include copy of A at the 2nd position 
print("\nThe data frame after insert() function is\n", v)



The data frame after insert() function is
     A  B  Copy of A   C
r1  1  5          1  11
r2  2  6          2  22
r3  3  7          3  33
r4  4  8          4  44


In [19]:

# deleting the whole column
# --> pop("column name")
v=pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]}, index=['r1', 'r2', 'r3', 'r4'])
p=v.pop("B") # will delete the column B
print("\nAfter deleting whole the column\n", p) # this will delete the column and print the values only but not the column name, and at the bottom of the answer, a message like name=B, dtype=32 will be displayed which indicates that the column mentioned in name is deleted.
print("\nAfter deleting the column the data frame is\n", v) # now this will print the data frame along with the names of remaining non deleted columns



After deleting whole the column
 r1    5
r2    6
r3    7
r4    8
Name: B, dtype: int64

After deleting the column the data frame is
     A
r1  1
r2  2
r3  3
r4  4


In [20]:
# deleting columns using 
# --> del variable_Name["column name"]
v=pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]}, index=['r1', 'r2', 'r3', 'r4'])
del v["A"] # this will delete the column A and the data frame is printed along with non deleted column names
print("\nAfter deleting desired column using dl var['name'] function is\n", v)



After deleting desired column using dl var['name'] function is
     B
r1  5
r2  6
r3  7
r4  8


### working with csv and Excel files

In [21]:
# csv file--> a csv formate is a plain text in which values are separated by commas

# XLS--> an xls file formate is an Excel sheets binary file formate which holds information about all the worksheets in a file including both content and formatting.

# creating a simple csv file 

# --> variable_name.to_csv("File name.csv", index=[] or False, header=[])
# index=false means there will not be any andex in the file, and header=[] is used to add the column names
c=np.array([[1,2,3,4,5],[11,22,33,44,55], [5,4,3,2,1],[55,44,33,22,11]])
cs=pd.DataFrame(c,  columns=['A', 'B', 'C', 'D', 'E']) # this will change np values in data frame
cs.to_csv("Example_file.csv", index=False, header=['A', 'B', 'C', 'D', 'E']) # this will create a csv file with Example_file name, without indexing and with column names as ABCDE
# this file will be saved in the same main folder where your code is saved
# print(cs) ## optional, just to check whether the output matches the csv file or not

In [22]:

# Reading a csv file 
# --> variable_name=pd.read_csv("Complete path along with //.csv", nrows=any_Number, or usecols=["column name"])
# --> nrows=num --> will read the number of rows and usecols=["name" or index number]--> will read the column data
# a sample csv file must be saved in hard disc to use it here
csv=pd.read_csv("Example_file.csv")
print(csv) # this will print the data included in file
print("--------------------------------------------")
csv_1=pd.read_csv("Example_file.csv", nrows=2)
print(csv_1) # this will print the data of only 2 top most rows of the file
print("--------------------------------------------")
csv_2=pd.read_csv("Example_file.csv", usecols=["C"])
print(csv_2) # this will print the data of only C column of the file
print("--------------------------------------------")


    A   B   C   D   E
0   1   2   3   4   5
1  11  22  33  44  55
2   5   4   3   2   1
3  55  44  33  22  11
--------------------------------------------
    A   B   C   D   E
0   1   2   3   4   5
1  11  22  33  44  55
--------------------------------------------
    C
0   3
1  33
2   3
3  33
--------------------------------------------


In [23]:
# skipping the rows from the file
# --> name=pd.read_csv("file name.csv", skip=[row index])
csv_3=pd.read_csv("Example_file.csv", skiprows=[0])
print(csv_3) # this will skip row number 0 and prints the rest of the data of a file.
print("---------------------------------------------")


    1   2   3   4   5
0  11  22  33  44  55
1   5   4   3   2   1
2  55  44  33  22  11
---------------------------------------------


In [24]:
# making a column to work as an index
# --> name=pd.read_csv("file name.csv", index_col["name" or index num])
csv_4=pd.read_csv("Example_file.csv", index_col=["A"])
print(csv_4) # this will print data after making column A as an index
print("---------------------------------------------")


     B   C   D   E
A                 
1    2   3   4   5
11  22  33  44  55
5    4   3   2   1
55  44  33  22  11
---------------------------------------------


In [25]:
# now making row as header/column names
# --> name=pd.read_csv("file name.csv", header=row num)
csv_5=pd.read_csv("Example_file.csv", header=2)
print(csv_5) # thi will print data after making row as header
print("---------------------------------------------")


   11  22  33  44  55
0   5   4   3   2   1
1  55  44  33  22  11
---------------------------------------------


In [26]:
# giving heading to the data
# --> name=pd.read_csv("file name.csv", names=["name", "name",....])
csv_6=pd.read_csv("Example_file.csv",names=["A=1st_v", "B=2nd_v", "C=3rd_v", "D=4th_v", "E=5th_v"])
print(csv_6) # this will print data frame with heading
print("---------------------------------------------")


  A=1st_v B=2nd_v C=3rd_v D=4th_v E=5th_v
0       A       B       C       D       E
1       1       2       3       4       5
2      11      22      33      44      55
3       5       4       3       2       1
4      55      44      33      22      11
---------------------------------------------


In [27]:
# converting dtypes of values in data frames
# --> name=pd.read_csv("file name.csv", dtype ={"name of column":"dtype to convert in"})
csv_7=pd.read_csv("Example_file.csv", dtype={"A":"float"})
print(csv_7) # this will print data after converting data type of column A 
print("---------------------------------------------")


      A   B   C   D   E
0   1.0   2   3   4   5
1  11.0  22  33  44  55
2   5.0   4   3   2   1
3  55.0  44  33  22  11
---------------------------------------------


### some functions on csv file


In [28]:
# to know the total number of indices in a data frame
# first have to read the csv file 
# making use of abive defined csv_7
# --> name.index
i=csv_7.index
print("\nThe total number of indices are --> ", i)
print("---------------------------------------------")



The total number of indices are -->  RangeIndex(start=0, stop=4, step=1)
---------------------------------------------


In [29]:
# in order to know the names of columns
c=csv_7.columns
print("The columns defined in data frame are --> ", c)
print("---------------------------------------------")


The columns defined in data frame are -->  Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
---------------------------------------------


In [30]:
# to display data of selected rows 
# --> csv.head(number)
h=csv_7.head() # this will print first 5 rows of data
h_1= csv_7.head(1) # this will print data of 1st row
print("\nThe first five rows are\n", h)
print("\nThe data of first row is \n", h_1)
print("---------------------------------------------")



The first five rows are
       A   B   C   D   E
0   1.0   2   3   4   5
1  11.0  22  33  44  55
2   5.0   4   3   2   1
3  55.0  44  33  22  11

The data of first row is 
      A  B  C  D  E
0  1.0  2  3  4  5
---------------------------------------------


In [31]:
# to display the bottom most data of selected rows
# --> csv.tail(num), if num is not given than it will print last five lines of data
t=csv_7.tail(2) 
print("\nthe data of last 2 lines is\n", t)# will print last 2 lines of data
print("---------------------------------------------")



the data of last 2 lines is
       A   B   C   D   E
2   5.0   4   3   2   1
3  55.0  44  33  22  11
---------------------------------------------


In [32]:
# in order to get values through a particular range using string slicing
# --> csv[slicing]
s=csv_7[1:4] # the last number is always n-1 --> 4-1=3
print(s) # this will print values from row 1 to the row 3 bcz 4-1
print("---------------------------------------------")


      A   B   C   D   E
1  11.0  22  33  44  55
2   5.0   4   3   2   1
3  55.0  44  33  22  11
---------------------------------------------


In [33]:
# changing index numbers into arrays
# --> csv.index.array
ch=csv_7.index.array
print("\nThe index nums in array formate is\n", ch)
print("---------------------------------------------")



The index nums in array formate is
 <PandasArray>
[0, 1, 2, 3]
Length: 4, dtype: int64
---------------------------------------------


In [34]:
# to change whole data frame into numpy
# --> csv.to_numpoy()
# --> variable=np.asarray(datafrmane name)
n=csv_7.to_numpy()
print("\nThe data frame changed into numpy is\n", n)
# now through another method
m=np.asarray(csv_7) 
print("\nData frame changed in numpy through np method\n", m) # will print the same result as above
print("---------------------------------------------")



The data frame changed into numpy is
 [[ 1.  2.  3.  4.  5.]
 [11. 22. 33. 44. 55.]
 [ 5.  4.  3.  2.  1.]
 [55. 44. 33. 22. 11.]]

Data frame changed in numpy through np method
 [[ 1.  2.  3.  4.  5.]
 [11. 22. 33. 44. 55.]
 [ 5.  4.  3.  2.  1.]
 [55. 44. 33. 22. 11.]]
---------------------------------------------


In [35]:
# printing data in descending order
# --> name.sort_index(axis=0 or 1 , ascending = false)
# axis=0 means to access the row and axis=1 means to access the column of data frame 
asc=csv_7.sort_index(axis=0, ascending=False) # will convert in descending 
print("\nThe descending ordered data frame is \n", asc)
print("---------------------------------------------")




The descending ordered data frame is 
       A   B   C   D   E
3  55.0  44  33  22  11
2   5.0   4   3   2   1
1  11.0  22  33  44  55
0   1.0   2   3   4   5
---------------------------------------------


In [36]:
# changing data from a data frame
# --> name.loc[row num, column num or "name"] = change
csv_8=pd.read_csv("Example_file.csv", dtype={"A":"float"})
csv_8.loc[0,"B"]="hello"
print(csv_8) # will print the data frame by changing its value at index=0 and Column B
print("---------------------------------------------")


      A      B   C   D   E
0   1.0  hello   3   4   5
1  11.0     22  33  44  55
2   5.0      4   3   2   1
3  55.0     44  33  22  11
---------------------------------------------


In [37]:
# fetching data of selected column and row
# --> name.loc[[row nums], ["column names"]]
d=csv_8.loc[[0,3], ["B","C"]]
print("\nThe desired values from the data are\n", d) # will print the values at index= 0 and 3 of column names B and C
print("---------------------------------------------")



The desired values from the data are
        B   C
0  hello   3
3     44  33
---------------------------------------------


In [38]:
# drop/remove any row or column from the data
# -->name.drop(index for row or "column name" , axis=0 for row and axis=1 for column)
# if in case the data contains any NAN value at any position than to remove it, use --> name.dropna(axis=0 for rows and axis=1 for columns)
# to remove any particular row which contains all NAN values of that row, use --> name.dropna(how="all")
# to remove any particular row which contains all NAN values along with the those which atleast contain one NAN value, use --> name.dropna(how="any")
# to remove any NAN value of any selected column, use --> name.dropna(subset=["name of column"])
dr=csv_8.drop("C", axis=1)
print("\nthe data frame after dropping a particular column\n", dr) # the column C will not be the part of data anymore
print("---------------------------------------------")



the data frame after dropping a particular column
       A      B   D   E
0   1.0  hello   4   5
1  11.0     22  44  55
2   5.0      4   2   1
3  55.0     44  22  11
---------------------------------------------


In [39]:
# to fill any NAN value, use --> name.fillna([value or "value"])-- this will fill all NAN values present in data
# to fill any NAN value in the particular column, use --> name.fillna({"name of column":value or "value", ....})
# to fill any NAN value with the previous data means same as the previous value, use --> name.fillna(method="ffill")
# to fill any NAN value with the next data means same as the previous value, use --> name.fillna(method="bfill")
# to fill any NAN values by suing axis 1 for column and o for row, use --> name.fillna(method="b/ffile", axis=1/0)
# to fill any NAN value to a certain limit, use --> name.fillna("value"/value, limit=num)-- will the NAN values to the limit defined


# Replace any value with other one
# --> name.replace(to_replace= value/"value", value=value/"value")
csv_9=pd.read_csv("Example_file.csv")
print("\nThe data frame before replace function is\n",csv_9)
r=csv_9.replace(to_replace= 1, value="hi") # this will replace all 1s with "hi" string 
print("\nThe data frame after replace function is\n",r)
print("---------------------------------------------")



The data frame before replace function is
     A   B   C   D   E
0   1   2   3   4   5
1  11  22  33  44  55
2   5   4   3   2   1
3  55  44  33  22  11

The data frame after replace function is
     A   B   C   D   E
0  hi   2   3   4   5
1  11  22  33  44  55
2   5   4   3   2  hi
3  55  44  33  22  11
---------------------------------------------


In [40]:
# replacing the selceted values to a certain range  
c=csv_9.replace([1,11,5], [2,22,7]) # will replace the values with givin values
print(c)
print("---------------------------------------------")


    A   B   C   D   E
0   2   2   3   4   7
1  22  22  33  44  55
2   7   4   3   2   2
3  55  44  33  22  22
---------------------------------------------


In [41]:

# merging two or more data frames that contain atleast one common column
# --> name.merge(df1,df2,..., on="common column name"), changing positions of dfs will also change the position in data frames
df1=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10]})
df2=pd.DataFrame({"A":[1,2,3,4,5], "C":[66,77,88,99,100]}) # here column A is common with common elements in both data frames
mg=pd.merge(df1,df2)# will merge A
print("\nthe merged data frame is \n", mg)
print("---------------------------------------------")



the merged data frame is 
    A   B    C
0  1   6   66
1  2   7   77
2  3   8   88
3  4   9   99
4  5  10  100
---------------------------------------------


In [42]:
# merging dataframes with atleast one or common element
df_1=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10]})
df_2=pd.DataFrame({"A":[1,2,3,4,88],"C":[66,77,88,99,100]}) # A is common but only one element is not common
mg_1=pd.merge(df_1,df_2, on="A") # will merge the common elements by skipping the uncommon ones
print("\nthe merged data frame with uncommon element is \n", mg_1)
print("---------------------------------------------")



the merged data frame with uncommon element is 
    A  B   C
0  1  6  66
1  2  7  77
2  3  8  88
3  4  9  99
---------------------------------------------


In [43]:
# concatenating the data frames 
# --> pd.concat([name1,name2], axis=0/1, keys=["name1", "name2",...])
# key=[] helps to add the names of two or more concatente=ing arrays
d1=pd.DataFrame({"A":[1,2,3,4,5], "B":[6,7,8,9,10]})
d2=pd.DataFrame({"A":[1,2,3,4,88],"B":[66,77,88,99,100]})
con_s=pd.concat([d1,d2], axis= 1) # axis=1 will concatenate the dataframe row wise, otherise, column wise
con_k=pd.concat([d1,d2], axis= 1, keys=["data_1", "data_2"])
print("\nThe concatenated data farme is \n", con_s)# this will simply print the concatenated data 
print("\nThe concatenated data farme with name is \n", con_k)# this will print the concatenated data with names
print("---------------------------------------------")



The concatenated data farme is 
    A   B   A    B
0  1   6   1   66
1  2   7   2   77
2  3   8   3   88
3  4   9   4   99
4  5  10  88  100

The concatenated data farme with name is 
   data_1     data_2     
       A   B      A    B
0      1   6      1   66
1      2   7      2   77
2      3   8      3   88
3      4   9      4   99
4      5  10     88  100
---------------------------------------------


In [44]:
# concatenating data frames with missing values
a_1=pd.DataFrame({"A":[1,2,4,5], "B":[6,7,8,9]}) # the array sizes must be same
a_2=pd.DataFrame({"A":[4,88],"C":[66,100]})# the array sizes must be same
con_1=pd.concat([a_1,a_2], axis=1)# will concatenate by adding NAN in the place of missing values
print("\nThe concatenated data farme with some missing values is \n", con_1)
print("---------------------------------------------")



The concatenated data farme with some missing values is 
    A  B     A      C
0  1  6   4.0   66.0
1  2  7  88.0  100.0
2  4  8   NaN    NaN
3  5  9   NaN    NaN
---------------------------------------------


In [45]:
# joing the data frames
# --> name1.join(name2)
j_1=pd.DataFrame({"A":[1,2,4,5], "B":[6,7,8,9]}) # the array sizes must be same
j_2=pd.DataFrame({"C":[4,88],"D":[66,100]})
j=j_1.join(j_2) # will join the data frames by placing NAN on missing values' place
print("\nThe joined data frames are\n", j)
print("---------------------------------------------")



The joined data frames are
    A  B     C      D
0  1  6   4.0   66.0
1  2  7  88.0  100.0
2  4  8   NaN    NaN
3  5  9   NaN    NaN
---------------------------------------------
