### Numpy is used over the list bcz it is faster than the lists in many ways.


In [1]:
# import it
import numpy as np

In [2]:
# way to create an array
a=np.array([1,2,3,4])
print("\n1D array without declaring the size\n", a)



1D array without declaring the size
 [1 2 3 4]


In [3]:
# incase we want to declare the size of the array
b= np.array([1,2,3,4] , dtype='int16') # not necessary to declare the  bydefault size is 32 bits
print("\n1D array with declaring the size\n",b)



1D array with declaring the size
 [1 2 3 4]


In [4]:
# way to create more than 1D array..... 2D
c=np.array([[1,2,3,4],[5,6,7,8]])
print("\nmore than  1D array\n",c)



more than  1D array
 [[1 2 3 4]
 [5 6 7 8]]


In [5]:
# In order to know the dimension means 1D, 2D etc...
print("\nThe dimension of array 'a' is \n", a.ndim) # will print 1 bcz the array A is a 1D
print("\nThe dimension of array 'c' is \n", c.ndim) # will print 1 bcz the array C is a 2D



The dimension of array 'a' is 
 1

The dimension of array 'c' is 
 2


In [6]:
# In order to get the shape --> eg (2,3) like matrices
print("\nThe shape of array 'c' is\n", c.shape) # will print (2,4) 2=rows and 4=columns



The shape of array 'c' is
 (2, 4)


In [7]:
# In order to know the Data type of array
print("\nThe dtype of array 'b' is\n", b.dtype) # will print int16 bcz size and dtype is defined
print("\nThe dtype of array 'a' is\n", a.dtype) # will print int32 by default



The dtype of array 'b' is
 int16

The dtype of array 'a' is
 int32


In [8]:
# In order to know the number of bytes occupied by the array
print("\nThe number of bytes space by array 'a' is", a.nbytes)
print("\nThe number of bytes space by array 'b' is", b.nbytes) # here the size is defined therefore will occupy less space than a nd c
print("\nThe number of bytes space by array 'c' is", c.nbytes)



The number of bytes space by array 'a' is 16

The number of bytes space by array 'b' is 8

The number of bytes space by array 'c' is 32


In [9]:
# In order to know the item size of the array
print("\n The item size of array 'a' is", a.itemsize)
print("\n The item size of array 'b' is", b.itemsize)
print("\n The item size of array 'c' is", c.itemsize)




 The item size of array 'a' is 4

 The item size of array 'b' is 2

 The item size of array 'c' is 4


In [10]:
# Getting the elements from an array using [row, column] manner
# Remember the index starts with 0
d=c[0,2] # the array c is defined at line#15
print("\n the element in row 0 and column 2 is", d) # will print 3 from row 0 and column 2

# Get all elements of the row [row, :]
e=c[0 ,:] # the rray c is defined at line#15
print("\nThe row 0 elements are\n", e) # will print all the elements of row 0 of array c

# Get all elements of the column [:,column]
f=c[:, 2] # the rray c is defined at line#15
print("\nThe column 2 elements are\n", f) # will print the elements of column 2 of array c

# To change the value from the array using [row, column]=num 
a[2]=5 # the row value is not given it is 1D
print("\n the values of previous array 'a' is changed\n", a) # will print the array with change in value in column 2
c[1,3]=11 # now the row and column values are given bcz it is 2D
print("\nThe values of prevoius array 'c' are chnaged\n", c)



 the element in row 0 and column 2 is 3

The row 0 elements are
 [1 2 3 4]

The column 2 elements are
 [3 7]

 the values of previous array 'a' is changed
 [1 2 5 4]

The values of prevoius array 'c' are chnaged
 [[ 1  2  3  4]
 [ 5  6  7 11]]


In [11]:
# Changing the entire row or column of an array using [row, :] or [:, column]
# Remember the array should be 1D or more
d=np.array([[11,22,33,44],[55,66,77,88],[2,3,1,4]])
d[2,:]=333 # will cahnge all the values of a row 2 of the array d
print("\nThe changed row values of array 'd' is\n", d)
d[:,2]=33 #This will change the values of column 2 of array d
print("\nThe changed column value of array 'd' is\n", d)

d[: , 3]=[22, 55, 77] # This will change the values of column 2 of array d
print("\nthe two different numbers changed in array 'd' \n", d)



The changed row values of array 'd' is
 [[ 11  22  33  44]
 [ 55  66  77  88]
 [333 333 333 333]]

The changed column value of array 'd' is
 [[ 11  22  33  44]
 [ 55  66  33  88]
 [333 333  33 333]]

the two different numbers changed in array 'd' 
 [[ 11  22  33  22]
 [ 55  66  33  55]
 [333 333  33  77]]


In [12]:
# 3D array
t=np.array([[[11,22,33,44],[44,33,22,11]],[[55,66,77,88],[88,77,66,55]]])
print("\nThe 3D array 't' is defined as\n", t)
print("\nThe shape of 3D array 't' is\n", t.shape)
print("\nThe number of dimension array 't' are \n",t.ndim)




The 3D array 't' is defined as
 [[[11 22 33 44]
  [44 33 22 11]]

 [[55 66 77 88]
  [88 77 66 55]]]

The shape of 3D array 't' is
 (2, 2, 4)

The number of dimension array 't' are 
 3


In [13]:
# To get the specific element using [array, row, colum]
# here [arra] defines the index of the matrix whether 0,1,2,...
tt=t[0,0,3] # this means matrix = 0, row = 0 and column = 3
print("\nThe element from 3d array 't' is\n", tt) # must print 4

# to get the matrices or whole array
ttt=t[:,1,:] # this will print the row 1 from both of the matrices  
print("\nThe part of 3D array is\n", ttt)



The element from 3d array 't' is
 44

The part of 3D array is
 [[44 33 22 11]
 [88 77 66 55]]


In [14]:
# To change the array elements
t[0,0,3]=4444
print("\nThe 3D array with element changed is \n", t)

t[:,0,:]=[[1,2,3,4],[4,3,2,1]] # this will change the row 0 elements of the array
print("\nThe array with changed row value\n", t)

print("----------------------------------------------------------")



The 3D array with element changed is 
 [[[  11   22   33 4444]
  [  44   33   22   11]]

 [[  55   66   77   88]
  [  88   77   66   55]]]

The array with changed row value
 [[[ 1  2  3  4]
  [44 33 22 11]]

 [[ 4  3  2  1]
  [88 77 66 55]]]
----------------------------------------------------------


In [15]:
# To make the different matrices
# to make an array of zeros like (shape)
d=np.zeros((2,3)) # will print the array of zeros of 2r and 3c 
print("\nmthe zero array of shape 2*3 is\n", d)

# to make an array of ones
d=np.ones((2,2)) # shape is 2*2
print("\nthe array of ones is \n", d)

# to make an array of any other number full((shape), number)
d=np.full((2,3,2), 33) # will make a 3D array of 33 number
print("\nthe 3D array of number is \n", d)

# to make an identity matrix --> identity(size)
i=np.identity(4) # will make identity matrix of size 4
print("\nThe 3D identity matrix is\n", i)

# to make an array of random decimal numbers --> random.rand(shape)
r=np.random.rand(2,2,2) # will make 3D array of random decimal numbers
print("\nThe random decimal 3d array is \n", r)

# to make an array of integer random nums --> random.randint(start num, end num, size=(shape))
r=np.random.randint(2,10, size=(2,3,2)) # will  make 3D array, the starting num is always excluded in the array
print("\nThe 3D integer rand0om array is \n", r)

print("-----------------------------------------------------")



mthe zero array of shape 2*3 is
 [[0. 0. 0.]
 [0. 0. 0.]]

the array of ones is 
 [[1. 1.]
 [1. 1.]]

the 3D array of number is 
 [[[33 33]
  [33 33]
  [33 33]]

 [[33 33]
  [33 33]
  [33 33]]]

The 3D identity matrix is
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

The random decimal 3d array is 
 [[[0.29947109 0.45743308]
  [0.79833523 0.94098839]]

 [[0.22189592 0.18693473]
  [0.33917634 0.76824604]]]

The 3D integer rand0om array is 
 [[[5 9]
  [9 9]
  [7 8]]

 [[7 5]
  [3 9]
  [2 4]]]
-----------------------------------------------------


In [16]:
# To repeat an array as many times as you want
# --> repeat(name, times)
r=np.array([[1,2,3,4]]) # first make the 2D array
rep=np.repeat(r, 3, axis=0)
print("\nThe repeated array is \n", rep)

print("--------------------------------------------------------")




The repeated array is 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
--------------------------------------------------------


In [17]:
# To copy the array elements into another one
# -->  .copy() 
a=np.array([1,2,3,4])
b=a.copy()
print("\nthe copied array is\n", b)

print("---------------------------------------------------------")



the copied array is
 [1 2 3 4]
---------------------------------------------------------


In [18]:
# subtracting, adding, multiplying, and dividing any number with an array
# we can apply any of the mathematical operation on arrays
a=np.array([2,4,6,8,10])
print("\nthe array after adding a num is \n", a+3)
print("\nthe array after sutracting a num is \n", a-3)
print("\nthe array after multiplying a num is \n", a*3)
print("\nthe array after dividing a num is \n", a/3)
print("\nThe array with power 2 is\n", a**2)



the array after adding a num is 
 [ 5  7  9 11 13]

the array after sutracting a num is 
 [-1  1  3  5  7]

the array after multiplying a num is 
 [ 6 12 18 24 30]

the array after dividing a num is 
 [0.66666667 1.33333333 2.         2.66666667 3.33333333]

The array with power 2 is
 [  4  16  36  64 100]


In [19]:
# +, -, /, * any of the arrays
a=np.array([2,4,6,8,10])
b=np.array([1,2,3,4,5])
print("\nThe array after adding two arrays is\n", a+b)
print("\nThe array after subtrating two arrays is\n", a-b)
print("\nThe array after multiplying two arrays is\n", a*b) # this multiplication is not same the matrix multiplication bcz in this multiplication the elements at respective positions are being multiplied.  Nut in matrix multipliocation it is necesary to have columns of 1st matrix = rows of 2nd
print("\nThe array after dividing two arrays is\n", a/b)



The array after adding two arrays is
 [ 3  6  9 12 15]

The array after subtrating two arrays is
 [1 2 3 4 5]

The array after multiplying two arrays is
 [ 2  8 18 32 50]

The array after dividing two arrays is
 [2. 2. 2. 2. 2.]


In [20]:
# trigonomatric functions on array
# --> np.trigonomatric identity (array)
a=np.array([90,180,270,360])
print("\nThe sin of array is \n", np.sin(a))
print("\nThe cos of array is \n", np.cos(a))
print("\nThe tan of array is \n", np.tan(a))




The sin of array is 
 [ 0.89399666 -0.80115264 -0.17604595  0.95891572]

The cos of array is 
 [-0.44807362 -0.59846007  0.98438195 -0.28369109]

The tan of array is 
 [-1.99520041  1.33869021 -0.17883906 -3.38014041]


In [21]:
# applaying Linear Algebra on the arrays
# multilplying arrays algebraically
# --np.matmul(array1, array2)
a=np.identity(3)
b=np.full((3,2), 3)
c=np.matmul(a,b)
print("\nTyhe multipied arrays are\n", c)

# to find out the determinant of array
# --> np.linalg.det(array)
# the matrix should be square in ty
a=np.identity(3)
d=np.linalg.det(a) # will print 1 bcz determinant of an identity matrix is always 1
print("\nThe detreminant of tyhe array is\n", d)

print("------------------------------------------------")



Tyhe multipied arrays are
 [[3. 3.]
 [3. 3.]
 [3. 3.]]

The detreminant of tyhe array is
 1.0
------------------------------------------------


In [22]:
#Some other mathematics operations
#to find the minimum element in an array
# --> np.min(array)
t=np.array([[[11,22,33,44],[44,33,22,11]],[[55,66,77,88],[88,77,66,55]]]) # Reused 3D array
min=np.min(t)
print("\nThe minimun element from an array is --> ", min)



The minimun element from an array is -->  11


In [23]:
# to find the minmum elements from each matrix
# --> np.min(array, axis=1)
# axis=0 will give all the values from row 0
c=np.array([[1,2,3,4],[5,6,7,8]])
min=np.min(c, axis=1)
print("\nAll the minimum elements from an array are\n", min)

# To find the maximum element from an array
# --> np.max(array)
t=np.array([[[11,22,33,44],[44,33,22,11]],[[55,66,77,88],[88,77,66,55]]])
max=np.max(t)
print("\nThe maximum element from an array is --> ", max)

# To find all the maximum values of an array
# --> np.max(array, axis=1)
# axis=0 will give all the values from row 0
c=np.array([[1,2,3,4],[5,6,7,8]])
max=np.max(c, axis=1)
print("\nAll the maximum elements of an array are\n", max)

# To find the total sum of all the elements of an array
# np.sum(array)
c=np.array([[1,2,3,4],[5,6,7,8]]) # elements of both of these will be added with each other
sum=np.sum(c)
print("\nThe sum of all the elements of an array is --> ", sum)



All the minimum elements from an array are
 [1 5]

The maximum element from an array is -->  88

All the maximum elements of an array are
 [4 8]

The sum of all the elements of an array is -->  36


In [24]:
# to add the the elements of one row with the other
# n--> np.sum(array, axis=0)
# if axis=1 this will yield the sum of all first row elements and sum of all 2nd row elements in matrix form
# in place of sum, other mathematical operations like squre root (sqrt), square (square), absolute(abs) etc can be performed in same manner
c=np.array([[1,2,3,4],[5,6,7,8]])
sum=np.sum(c, axis=0)
print("\nthe sum elements  of one row with other is\n", sum) 
sum=np.sum(c, axis=1)
print(sum)

print("--------------------------------------------------")



the sum elements  of one row with other is
 [ 6  8 10 12]
[10 26]
--------------------------------------------------


In [25]:
# Reshaping the matrix of own choice
# --> array.reshape((row, column))
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.shape) # will yield (2,4)
reshape=c.reshape((4,2)) # will make an array of 4 rows and 2 columns
print("\nThe reshapped aray is \n", reshape)


(2, 4)

The reshapped aray is 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
# combinning two matrices into a single matrix VERTICALLY
# --> np.vstack([array1, array2, ...])
v1=np.array([[1,2,3,4], [11,22,33,44]])
v2=np.array([[5,6,7,8], [55,66,77,88]])
single=np.vstack([v1, v2])
print("\nthe array after combination is\n", single)

# we can also use any matrix to be included many times in a single matrix
v1=np.array([[1,2,3,4], [11,22,33,44]])
v2=np.array([[5,6,7,8], [55,66,77,88]])
singlev=np.vstack([v1, v2, v1, v2,v1,v2,v2])
print("\nthe array after combination is\n", singlev)

# combinning two matrices into a single matrix HORIZONTALLY
# --> np.hstack([array1, array2])
h1=np.array([1,2,3,4])
h2=np.ones(4)
singleh=np.hstack([h1,h2])
print("\nThe array after combination is\n", singleh)

print("----------------------------------------------")



the array after combination is
 [[ 1  2  3  4]
 [11 22 33 44]
 [ 5  6  7  8]
 [55 66 77 88]]

the array after combination is
 [[ 1  2  3  4]
 [11 22 33 44]
 [ 5  6  7  8]
 [55 66 77 88]
 [ 1  2  3  4]
 [11 22 33 44]
 [ 5  6  7  8]
 [55 66 77 88]
 [ 1  2  3  4]
 [11 22 33 44]
 [ 5  6  7  8]
 [55 66 77 88]
 [ 5  6  7  8]
 [55 66 77 88]]

The array after combination is
 [1. 2. 3. 4. 1. 1. 1. 1.]
----------------------------------------------


In [28]:
# load the data from a file
# --> np.genfromtxt('name of file.extension', delimiter='data separated by (, or other symbol)')
# first make a file and add some data into it and than load it in the above mentioned manner
# File should be saved in the sme folder in which program is already saved
# ??????????????????The following program is throwing error of file not found ?????????????????????
# load_data=np.genfromtxt('sample.txt' , delimiter=',')
# print("\nThe loaded data from a file", load_data.dtype(int))

# to get the output in Boolean formate
# True or False output by comparing the elements
v1=np.array([[1,2,3,4], [11,22,33,44]])
v2=np.array([[5,6,7,8], [55,66,77,88]])
singlev=np.vstack([v1, v2, v1, v2,v1,v2,v2])
print("\nthe Boolean answer in an array\n", singlev>10) # will compare the elements with 10 and gives the output in True or False manner 

# to get the elements after comparing them in an array formate
# --> array[array compare]
v1=np.array([[1,2,3,4], [11,22,33,44]])
v2=np.array([[5,6,7,8], [55,66,77,88]])
single=np.vstack([v1, v2])
print("\nthe elements in anarray after comparing\n",single[single >5]) # will print all the elements from an array into the array formate

#------------------------------------ the end --------------------------------------


the Boolean answer in an array
 [[False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False False False False]
 [ True  True  True  True]]

the elements in anarray after comparing
 [11 22 33 44  6  7  8 55 66 77 88]
